global:
  evaluation_interval: 30s
  scrape_interval: 30s
scrape_configs:
- job_name: ai_trading_system
  metrics_path: /metrics
  scrape_interval: 30s
  static_configs:
  - targets:
    - localhost:9091
