# Comprehensive integrated configuration for OrchestratorAgent
# Combines all functionality: training, evaluation, live trading, scheduling

paths:
  data_dir_raw: 'data/raw_orch_integrated/'
  data_dir_processed: 'data/processed_orch_integrated/'
  scalers_dir: 'data/scalers_orch_integrated/'
  model_save_dir: 'models/orch_integrated/'
  tensorboard_log_dir: 'logs/tensorboard_orch_integrated/'
  reports_dir: 'reports/orch_integrated/'

ibkr_connection: # IBKR connection settings for live trading
  host: '127.0.0.1'
  port: 7497 # Paper TWS
  clientId: 105
  timeout_seconds: 10
  readonly: false # For live trading, this must be false
  account_id: "DUxxxxxxx" # Example Paper Account ID, replace with actual if testing live

feature_engineering:
  features: ['RSI', 'EMA', 'Time', 'VWAP'] # Comprehensive feature set
  rsi: {'window': 14}
  ema: {'windows': [10, 20], 'ema_diff': True}
  vwap: {'window': None, 'group_by_day': True } # Daily VWAP
  time_features: ['hour_of_day', 'day_of_week'] # Raw time features
  sin_cos_encode: ['hour_of_day', 'day_of_week'] # Which of the time_features to sin/cos encode
  lookback_window: 5 # For RL agent's observation sequence
  # Columns to be scaled by StandardScaler
  feature_cols_to_scale: 
    - 'rsi_14'
    - 'ema_10'
    - 'ema_20'
    - 'ema_diff'
    - 'vwap_deviation' # Assuming vwap_deviation is generated
    - 'hour_sin'       # Scaled sin/cos encoded features
    - 'hour_cos'
    - 'day_of_week_sin'
    - 'day_of_week_cos'
  # Final columns to be included in the observation sequence for the model
  observation_feature_cols: 
    - 'rsi_14'
    - 'ema_10'
    - 'ema_20'
    - 'ema_diff'
    - 'vwap_deviation'
    - 'hour_sin'
    - 'hour_cos'
    - 'day_of_week_sin'
    - 'day_of_week_cos'

environment: # Parameters for IntradayTradingEnv
  initial_capital: 100000.0 # Increased capital for more realistic trading
  transaction_cost_pct: 0.0005 # Realistic transaction cost
  reward_scaling: 1.0
  max_episode_steps: null # null means use length of data
  log_trades_in_env: True
  position_sizing_pct_capital: 0.25 # For env's internal sizing if used
  trade_cooldown_steps: 1 # Cooldown of 1 step in env

training:
  total_timesteps: 10000 # Increased for better training
  checkpoint_freq: 1000
  console_log_interval_episodes: 10 # SB3 model.learn log_interval for episodes
  data_duration_for_fetch: "30 D" # Longer training period
  use_eval_callback: true # Enable evaluation during training
  eval_freq: 2000 # Frequency of evaluation if EvalCallback is used

evaluation:
  metrics: ['total_return', 'sharpe_ratio', 'max_drawdown', 'num_trades', 'win_rate', 'profit_factor']
  data_duration_for_fetch: "10 D" # For DataAgent fetching historical data for evaluation runs

data_preprocessing:
  impute_missing: True
  normalize: False # Normalization is handled by FeatureAgent's StandardScaler

data_augmentation:
  noise_injection: true # Enable for more robust training
  noise_level: 0.01
  random_scaling: true
  scale_min: 0.98
  scale_max: 1.02
  window_slicing: false # If true, slices training data to 'window_size'
  window_size: 60

# Walk-forward validation settings
walk_forward:
  enabled: false # Set to true to run walk-forward in Orchestrator __main__
  overall_start_date: "2023-01-01"
  overall_end_date: "2023-06-30"
  train_window_days: 90
  eval_window_days: 30
  step_days: 30 # How many days to step forward for the next fold
  data_interval: "1min" # Interval for data used in walk-forward
  use_cached_data: false

# Scheduling settings for automated retraining
scheduling:
  retrain_symbol: "AAPL"
  retrain_interval: "1min"
  retrain_data_start_offset_days: 90 # Use data from 90 days ago
  retrain_data_end_offset_days: 1    # Up to yesterday
  evaluate_after_retrain_duration_days: 14 # Evaluate on last 2 weeks of data
  use_cached_data_for_scheduled_run: false

# Live trading specific configurations
live_trading:
  enabled: false # Master switch for live trading mode - SET TO TRUE TO ENABLE
  symbol: "AAPL" # Default symbol for live trading
  data_interval: "5 secs" # Interval for live data from DataAgent
  production_model_path: "models/production/best_model.zip" # Path to production model
  
  trade_quantity_type: "fixed_shares" # Options: "fixed_shares", "percent_of_capital", "fixed_notional"
  trade_quantity_value: 10.0 # Value for the chosen type
  
  order_type: "MKT" # Default order type: "MKT", "LMT"
  limit_price_offset_pct: 0.001 # For LMT orders: offset from current price
  time_in_force: "DAY" # Order TIF: "DAY", "GTC"
  
  contract_details: # Contract specifications
    sec_type: "STK"
    exchange: "SMART" # Use "SMART" for IB's smart routing
    currency: "USD"
    primary_exchange: "NASDAQ" # Important for some US stocks

  portfolio_sync_interval_minutes: 15 # How often to sync local portfolio with broker
  historical_warmup_bars: 200 # Number of historical bars to feed FeatureAgent at start
  
  market_open_time: "09:30:00"   # US Equities market open
  market_close_time: "16:00:00"  # US Equities market close
  market_time_zone: "America/New_York" # IANA time zone for market times
  
  # Risk management for live trading
  max_positions: 5 # Maximum number of concurrent positions
  max_daily_trades: 50 # Maximum trades per day
  position_size_limit_pct: 0.1 # Max 10% of portfolio per position
  stop_loss_pct: 0.05 # 5% stop loss
  take_profit_pct: 0.10 # 10% take profit
  
  # Emergency controls
  emergency_liquidate_on_drawdown_pct: 0.10 # Liquidate all if 10% drawdown
  pause_trading_on_consecutive_losses: 5 # Pause after 5 consecutive losses
  daily_loss_limit_pct: 0.05 # Stop trading if daily loss exceeds 5%

# AI Agents configuration (if using advanced AI features)
ai_agents:
  enabled: false # Set to true to enable AI-powered data provisioning
  use_group_agents: false # Whether to use group AI agents
  data_provisioning:
    enabled: false
    provider: "openai" # or other AI provider
    model: "gpt-4"
    max_tokens: 1000