default_data_params:
  interval: 1min
  symbol: SPY
  use_rth: true
  what_to_show: TRADES
environment:
  initial_capital: 100000.0
  log_trades_in_env: true
  max_episode_steps: null
  position_sizing_pct_capital: 0.25
  reward_scaling: 1.0
  trade_cooldown_steps: 0
  transaction_cost_pct: 0.0005
evaluation:
  data_duration_for_fetch: 90 D
  metrics:
  - total_return_pct
  - sharpe_ratio
  - max_drawdown_pct
  - sortino_ratio
  - calmar_ratio
  - avg_win_loss_ratio
  - profit_factor
  - num_trades
  - win_rate_pct
  - avg_trade_duration
  - turnover_ratio_period
feature_engineering:
  ema:
    ema_diff:
      fast_ema_idx: 0
      slow_ema_idx: 1
    windows:
    - 10
    - 20
    - 50
  feature_cols_to_scale:
  - rsi_14
  - ema_10
  - ema_20
  - ema_50
  - vwap_deviation
  features_to_calculate:
  - RSI
  - EMA
  - VWAP
  - Time
  lookback_window: 5
  observation_feature_cols:
  - rsi_14
  - ema_10
  - ema_20
  - vwap_deviation
  order_book_imbalance:
    levels_to_consider: 5
  rsi:
    window: 14
  time:
    sin_cos_encode:
    - hour_of_day
    - minute_of_hour
    time_features:
    - hour_of_day
    - minute_of_hour
    - day_of_week
  vwap:
    calculate_deviation: true
global_seed: 42
ibkr_connection:
  clientId: 100
  host: 127.0.0.1
  port: 7497
  timeout_seconds: 10
live_trading:
  data_interval: 1min
  enabled: false
  production_model_path: models/production/best_model.zip
  trade_quantity_type: fixed_shares
  trade_quantity_value: 100
paths:
  application_log_dir: logs/
  data_dir_processed: data/processed/
  data_dir_raw: data/raw/
  model_save_dir: models/
  reports_dir: reports/
  scalers_dir: data/scalers/
  tensorboard_log_dir: logs/tensorboard/
project_name: IntradayRLTrader
risk:
  curriculum:
    enabled: false
    logic: and
    use_perf_trigger: false
  dd_limit: 0.02
  eval_dd_limit: 0.02
  include_risk_features: true
  penalty_lambda: 0.5
  vol_window: 60
scheduling:
  evaluate_after_retrain_duration_days: 7
  retrain_cron_schedule: 0 0 * * 0
  retrain_data_end_offset_days: 1
  retrain_data_start_offset_days: 30
  retrain_interval: 1min
  retrain_symbol: AAPL
  use_cached_data_for_scheduled_run: false
training:
  checkpoint_freq: 50000
  data_duration_for_fetch: 365 D
  eval_freq: 100000
  log_interval: 100
  total_timesteps: 1000
  use_eval_callback: false
version: 0.1.0
