data_augmentation:
  noise_injection: true
  noise_level: 0.02
  random_scaling: true
  scale_max: 1.02
  scale_min: 0.98
  window_size: 60
  window_slicing: false
data_preprocessing:
  impute_missing: true
  normalize: false
environment:
  initial_capital: 50000.0
  log_trades_in_env: true
  position_sizing_pct_capital: 0.25
  reward_scaling: 1.0
  trade_cooldown_steps: 0
  transaction_cost_pct: 0.001
evaluation:
  data_duration_for_fetch: 5 D
  metrics:
  - total_return
  - num_trades
feature_engineering:
  ema:
    windows:
    - 10
    - 20
  feature_cols_to_scale:
  - rsi_14
  - ema_10
  - ema_20
  - hour_of_day
  features:
  - RSI
  - EMA
  - Time
  lookback_window: 3
  observation_feature_cols:
  - rsi_14
  - ema_10
  - ema_20
  - hour_of_day
  - Close
  rsi:
    window: 14
  time:
  - hour_of_day
ibkr_connection: null
paths:
  data_dir_processed: data/processed_orch_test/
  data_dir_raw: data/raw_orch_test/
  model_save_dir: models/orch_test/
  reports_dir: reports/orch_test/
  scalers_dir: data/scalers_orch_test/
  tensorboard_log_dir: logs/tensorboard_orch_test/
scheduling:
  evaluate_after_retrain_duration_days: 5
  retrain_data_end_offset_days: 7
  retrain_data_start_offset_days: 30
  retrain_interval: 1min
  retrain_symbol: AAPL
  use_cached_data_for_scheduled_run: false
training:
  checkpoint_freq: 500
  data_duration_for_fetch: 10 D
  log_interval: 50
  total_timesteps: 2000
