# config/risk_limits_v2.yaml
# RiskAgentV2 compatible configuration
# This format is required for RiskAgentV2.from_yaml() method

# Calculator configurations
calculators:
  drawdown:
    enabled: true
    config:
      lookback_periods: [1, 5, 20]
      min_periods: 1
  
  turnover:
    enabled: true
    config:
      hourly_window_minutes: 60
      daily_window_hours: 24
      use_absolute_values: true
  
  ulcer_index:
    enabled: true
    config:
      lookback_periods: [14, 30]
  
  drawdown_velocity:
    enabled: true
    config:
      velocity_window: 5
  
  expected_shortfall:
    enabled: true
    config:
      confidence_level: 0.95  # 95% confidence level (5% tail risk)
      lookback_periods: [20, 60]
  
  kyle_lambda:
    enabled: true
    config:
      estimation_window: 20
  
  depth_shock:
    enabled: true
    config:
      shock_threshold: 0.1
  
  feed_staleness:
    enabled: true
    config:
      staleness_threshold_seconds: 30
  
  latency_drift:
    enabled: true
    config:
      baseline_latency_ms: 10
      drift_threshold: 2.0
  
  adv_participation:
    enabled: true
    config:
      adv_lookback_days: 20
      participation_threshold: 0.05
  
  # VaR Calculator
  var:
    enabled: true
    config:
      confidence_levels: [0.95, 0.99, 0.999]
      window_days: 250
      method: "parametric"
      distribution: "normal"
      min_observations: 30
  
  # Stress Test Calculator
  stress_test:
    enabled: true
    config:
      scenarios: ["historical", "monte_carlo", "factor_shock"]
      confidence_levels: [0.95, 0.99, 0.999]
      monte_carlo_runs: 10000
      factor_shocks: [1, 2, 3, 5]
      historical_scenarios:
        financial_crisis_2008:
          start_date: "2008-09-01"
          end_date: "2008-12-31"
          description: "Financial Crisis 2008"
        covid_crash_2020:
          start_date: "2020-02-20"
          end_date: "2020-04-30"
          description: "COVID-19 Market Crash 2020"

# Risk policies and rules
policies:
  - policy_id: "main_risk_policy"
    policy_name: "Main Risk Policy"
    rules:
      # Drawdown limits
      - rule_id: "daily_drawdown_limit"
        rule_name: "Daily Drawdown Limit"
        rule_type: "threshold"
        field: "daily_drawdown"
        threshold: -0.02  # -2% (from original config)
        operator: "lt"
        action: "halt"
        severity: "critical"
      
      - rule_id: "max_drawdown_warning"
        rule_name: "Max Drawdown Warning"
        rule_type: "threshold"
        field: "max_drawdown"
        threshold: -0.05  # -5% warning level
        operator: "lt"
        action: "warn"
        severity: "medium"
      
      # Turnover limits
      - rule_id: "hourly_turnover_limit"
        rule_name: "Hourly Turnover Limit"
        rule_type: "threshold"
        field: "hourly_turnover_ratio"
        threshold: 5.0  # 5x capital per hour (from original config)
        operator: "gt"
        action: "block"
        severity: "high"
      
      - rule_id: "daily_turnover_limit"
        rule_name: "Daily Turnover Limit"
        rule_type: "threshold"
        field: "total_turnover_ratio"
        threshold: 20.0  # 20x capital per day (from original config)
        operator: "gt"
        action: "halt"
        severity: "critical"
      
      # Risk score limits
      - rule_id: "overall_risk_warning"
        rule_name: "Overall Risk Warning"
        rule_type: "threshold"
        field: "overall_risk_score"
        threshold: 0.7
        operator: "gt"
        action: "warn"
        severity: "medium"
      
      - rule_id: "overall_risk_critical"
        rule_name: "Overall Risk Critical"
        rule_type: "threshold"
        field: "overall_risk_score"
        threshold: 0.9
        operator: "gt"
        action: "halt"
        severity: "critical"
      
      # VaR Limit Rules (MONITORING MODE - will enforce when FP < 1/week)
      - rule_id: "var_95_limit"
        rule_name: "VaR 95% Limit"
        rule_type: "threshold"
        field: "var_95"
        threshold: 100000  # $100k
        operator: "gt"
        action: "warn"     # Monitoring mode
        severity: "medium"
        monitoring_mode: true
        enforcement_enabled: false
      
      - rule_id: "var_99_limit"
        rule_name: "VaR 99% Limit"
        rule_type: "threshold"
        field: "var_99"
        threshold: 200000  # $200k
        operator: "gt"
        action: "throttle" # Will throttle when enforcement enabled
        severity: "high"
        monitoring_mode: true
        enforcement_enabled: false
      
      - rule_id: "var_999_limit"
        rule_name: "VaR 99.9% Limit"
        rule_type: "threshold"
        field: "var_999"
        threshold: 500000  # $500k
        operator: "gt"
        action: "halt"     # Will halt when enforcement enabled
        severity: "critical"
        monitoring_mode: true
        enforcement_enabled: false
      
      # Stress Test Rules (MONITORING MODE)
      - rule_id: "stress_test_worst_case"
        rule_name: "Stress Test Worst Case Loss"
        rule_type: "threshold"
        field: "stress_worst_case"
        threshold: 1000000  # $1M
        operator: "gt"
        action: "reduce_position"
        severity: "high"
        monitoring_mode: true
        enforcement_enabled: false
      
      - rule_id: "stress_test_scenario_failures"
        rule_name: "Stress Test Scenario Failures"
        rule_type: "threshold"
        field: "failed_scenarios"
        threshold: 3
        operator: "gt"
        action: "warn"
        severity: "medium"
        monitoring_mode: true
        enforcement_enabled: false
      
      # Tail Risk Rules
      - rule_id: "expected_shortfall_99"
        rule_name: "Expected Shortfall 99% Limit"
        rule_type: "threshold"
        field: "expected_shortfall_99"
        threshold: 250000  # $250k
        operator: "gt"
        action: "throttle"
        severity: "high"
        monitoring_mode: true
        enforcement_enabled: false
      
      # Concentration Risk Rules
      - rule_id: "max_position_concentration"
        rule_name: "Maximum Position Concentration"
        rule_type: "threshold"
        field: "max_position_weight"
        threshold: 0.20  # 20%
        operator: "gt"
        action: "reduce_position"
        severity: "medium"
        monitoring_mode: true
        enforcement_enabled: false
      
      # Leverage Rules
      - rule_id: "gross_leverage_limit"
        rule_name: "Gross Leverage Limit"
        rule_type: "threshold"
        field: "gross_leverage"
        threshold: 3.0  # 3x
        operator: "gt"
        action: "reduce_position"
        severity: "high"
        monitoring_mode: true
        enforcement_enabled: false

# Active policy
active_policy: "main_risk_policy"

# VaR/Stress Test Enforcement Configuration
enforcement:
  # Enforcement mode: monitoring, gradual, full
  mode: "monitoring"
  
  # False positive threshold for automatic enforcement enablement
  false_positive_threshold_per_week: 1.0
  
  # Monitoring period for false positive analysis
  monitoring_period_days: 30
  
  # VaR limits for enforcement
  var_limits:
    var_95_limit: 100000    # $100k
    var_99_limit: 200000    # $200k
    var_999_limit: 500000   # $500k
  
  # Stress test limits
  stress_limits:
    max_stress_loss: 1000000      # $1M
    max_scenario_failures: 3
    max_tail_ratio: 1.5
  
  # Audit logging configuration
  audit:
    enabled: true
    log_directory: "logs/risk_audit"
    max_file_size_mb: 100
    max_files: 30
    compress_old_files: true
    async_logging: true
  
  # Prometheus metrics configuration
  metrics:
    enabled: true
    namespace: "risk"
    subsystem: "management"
    
  # Sensor configurations for enforcement
  sensors:
    var_breach:
      monitoring_mode: true
      enforcement_enabled: false
      false_positive_threshold: 1.0
    
    stress_test:
      monitoring_mode: true
      enforcement_enabled: false
      false_positive_threshold: 1.0
    
    tail_risk:
      monitoring_mode: true
      enforcement_enabled: false
      es_99_limit: 250000
      tail_ratio_threshold: 1.5
    
    concentration:
      monitoring_mode: true
      enforcement_enabled: false
      max_single_position_pct: 0.20
      max_herfindahl_index: 0.25
    
    leverage:
      monitoring_mode: true
      enforcement_enabled: false
      max_gross_leverage: 3.0
      max_net_leverage: 2.0
      max_margin_utilization: 0.80

# Legacy limits (for backward compatibility)
limits:
  max_daily_drawdown_pct: 0.02
  max_hourly_turnover_ratio: 5.0
  max_daily_turnover_ratio: 20.0
  halt_on_breach: true
  liquidate_on_halt: false