env_terminate_on_turnover_breach: false
env_turnover_penalty_factor: 0.015
env_turnover_termination_threshold_multiplier: 2.0
halt_on_breach: true
max_daily_drawdown_pct: 0.40  # Relaxed from 2.5% to 40% for training
max_daily_turnover_ratio: 20.0
max_hourly_turnover_ratio: 5.0
