# config/risk_limits.yaml
# Configuration for risk management parameters.

# --- Drawdown Limits ---
max_daily_drawdown_pct: 0.02

# --- Turnover Limits ---
max_hourly_turnover_ratio: 5.0
max_daily_turnover_ratio: 20.0

# --- General Risk Behavior ---
halt_on_breach: true
liquidate_on_halt: false

# --- Environment-Specific Risk Settings ---
env_turnover_penalty_factor: 0.01
env_terminate_on_turnover_breach: false
env_turnover_termination_threshold_multiplier: 2.0

# --- Basic Risk Limits ---
var_limit:
  enabled: true
  threshold: 2000000
  action: BLOCK

volatility_limit:
  enabled: true
  threshold: 0.35
  action: BLOCK

concentration_limit:
  enabled: true

greeks_limit:
  enabled: true

# --- Sensor-Based Risk Limits ---
feed_staleness_limit:
  enabled: true
  threshold: 1000
  action: KILL_SWITCH
  priority: CRITICAL

drawdown_velocity_limit:
  enabled: true
  threshold: 0.01
  action: KILL_SWITCH
  priority: CRITICAL

ulcer_index_limit:
  enabled: true
  threshold: 5.0
  action: BLOCK
  priority: HIGH

expected_shortfall_limit:
  enabled: true
  threshold: 0.03
  action: BLOCK
  priority: HIGH

kyle_lambda_limit:
  enabled: true
  threshold: 0.0002
  action: THROTTLE
  priority: HIGH

depth_shock_limit:
  enabled: true
  threshold: 0.05
  action: THROTTLE
  priority: HIGH

latency_drift_limit:
  enabled: true
  threshold: 0.50
  action: ALERT
  priority: MEDIUM

adv_participation_limit:
  enabled: true
  threshold: 0.20
  action: MONITOR
  priority: LOW

# --- Sensor Configuration ---
sensor_config:
  feed_staleness:
    enabled: true
    critical_feeds: ["market_data", "order_book", "trades"]
    
  drawdown_velocity:
    velocity_window: 10
    min_periods: 5
    
  ulcer_index:
    lookback_period: 14
    min_periods: 5
    
  expected_shortfall:
    confidence_level: 0.95
    lookback_period: 100
    min_periods: 20
    
  kyle_lambda:
    lookback_period: 50
    min_periods: 10
    impact_decay: 0.9
    
  depth_shock:
    max_impact_threshold: 0.10
    depth_levels: 5
    impact_model: "linear"
    
  latency_drift:
    baseline_window: 1000
    current_window: 100
    percentile: 99.9
    
  adv_participation:
    adv_lookback_days: 20
    participation_threshold: 0.20
    min_volume_days: 5

# --- Event Routing ---
event_routing:
  CRITICAL:
    max_latency_us: 100
    queue_size: 1000
    workers: 1
    
  HIGH:
    max_latency_us: 1000
    queue_size: 5000
    workers: 2
    
  MEDIUM:
    max_latency_us: 10000
    queue_size: 10000
    workers: 4
    
  LOW:
    max_latency_us: 100000
    queue_size: 50000
    workers: 2

# --- Observability Settings ---
observability:
  prometheus_enabled: true
  metrics:
    calc_latency_histogram: true
    breaches_counter: true
    sensor_health_gauge: true
    
  audit_trail:
    enabled: true
    sink: "JsonAuditSink"
    include_sensor_values: true
    
  performance_monitoring:
    latency_percentiles: [50, 95, 99, 99.9]
    alert_on_slo_breach: true