algorithm_name: DQN
algorithm_params:
  buffer_size: 5000
  learning_rate: 0.001
  policy: MlpPolicy
  verbose: 0
c51_features:
  dueling_nets: false
  n_step_returns: 1
  use_noisy_nets: false
  use_per: false
